/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;


import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;


/**
 *
 * @author HiHi
 */
public class DangKyForm extends javax.swing.JFrame {

    /**
     * Creates new form DangNhapForm
     */
    public DangKyForm() {
        this.setUndecorated(true);
        initComponents();
        this.setSize(850, 540);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setBackground(new Color(0, 0, 0, 0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMinimize = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        btnDangNhap = new keeptoo.KGradientPanel();
        lbDangNhap = new javax.swing.JLabel();
        lbTenNguoiDung = new javax.swing.JLabel();
        tfTenNguoiDung = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        lbNgaySinh = new javax.swing.JLabel();
        tfTaiKhoan = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        lbTaiKhoan = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        lbMatKhau = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        lbXacNhanMatKhau = new javax.swing.JLabel();
        tfMatKhau = new javax.swing.JPasswordField();
        tfXNMatKhau = new javax.swing.JPasswordField();
        lbThongBao = new javax.swing.JLabel();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        lbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageGiaoDien/minus_math_30px.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        getContentPane().add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, 40));

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageGiaoDien/multiply_30px.png"))); // NOI18N
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 40, 40));

        btnDangNhap.setBackground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setToolTipText("");
        btnDangNhap.setkBorderRadius(50);
        btnDangNhap.setkEndColor(new java.awt.Color(255, 255, 255));
        btnDangNhap.setkFillBackground(false);
        btnDangNhap.setkGradientFocus(300);
        btnDangNhap.setkStartColor(new java.awt.Color(102, 102, 102));
        btnDangNhap.setkTransparentControls(false);
        btnDangNhap.setOpaque(false);
        btnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseExited(evt);
            }
        });
        btnDangNhap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbDangNhap.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbDangNhap.setForeground(new java.awt.Color(51, 51, 51));
        lbDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDangNhap.setText("Đăng Nhập");
        lbDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDangNhapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbDangNhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbDangNhapMouseExited(evt);
            }
        });
        btnDangNhap.add(lbDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 475, 170, 50));

        lbTenNguoiDung.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lbTenNguoiDung.setForeground(new java.awt.Color(51, 51, 51));
        lbTenNguoiDung.setText("Tên Người Dùng");
        getContentPane().add(lbTenNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 190, 30));

        tfTenNguoiDung.setBackground(new java.awt.Color(51, 51, 51));
        tfTenNguoiDung.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tfTenNguoiDung.setForeground(new java.awt.Color(51, 51, 51));
        tfTenNguoiDung.setBorder(null);
        tfTenNguoiDung.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfTenNguoiDung.setNextFocusableComponent(tfMatKhau);
        tfTenNguoiDung.setOpaque(false);
        getContentPane().add(tfTenNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 290, 35));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 290, -1));

        lbEmail.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(51, 51, 51));
        lbEmail.setText("Email");
        getContentPane().add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 190, 30));

        tfEmail.setBackground(new java.awt.Color(51, 51, 51));
        tfEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tfEmail.setForeground(new java.awt.Color(51, 51, 51));
        tfEmail.setBorder(null);
        tfEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfEmail.setNextFocusableComponent(tfMatKhau);
        tfEmail.setOpaque(false);
        getContentPane().add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 290, 35));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 290, -1));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 190, 2));

        lbNgaySinh.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lbNgaySinh.setForeground(new java.awt.Color(51, 51, 51));
        lbNgaySinh.setText("Ngày Sinh");
        getContentPane().add(lbNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 190, 30));

        tfTaiKhoan.setBackground(new java.awt.Color(51, 51, 51));
        tfTaiKhoan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tfTaiKhoan.setForeground(new java.awt.Color(51, 51, 51));
        tfTaiKhoan.setBorder(null);
        tfTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfTaiKhoan.setNextFocusableComponent(tfMatKhau);
        tfTaiKhoan.setOpaque(false);
        getContentPane().add(tfTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 290, 35));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 290, -1));

        lbTaiKhoan.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lbTaiKhoan.setForeground(new java.awt.Color(51, 51, 51));
        lbTaiKhoan.setText("Tài Khoản");
        getContentPane().add(lbTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 190, 30));
        getContentPane().add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 290, -1));

        lbMatKhau.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lbMatKhau.setForeground(new java.awt.Color(51, 51, 51));
        lbMatKhau.setText("Mật Khẩu");
        getContentPane().add(lbMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 190, 30));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 290, -1));

        lbXacNhanMatKhau.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lbXacNhanMatKhau.setForeground(new java.awt.Color(51, 51, 51));
        lbXacNhanMatKhau.setText("Xác Nhận Mật Khẩu");
        getContentPane().add(lbXacNhanMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 190, 30));

        tfMatKhau.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfMatKhau.setText("jPasswordField1");
        tfMatKhau.setBorder(null);
        tfMatKhau.setOpaque(false);
        tfMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMatKhauActionPerformed(evt);
            }
        });
        getContentPane().add(tfMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 290, 35));

        tfXNMatKhau.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfXNMatKhau.setText("jPasswordField2");
        tfXNMatKhau.setBorder(null);
        tfXNMatKhau.setOpaque(false);
        getContentPane().add(tfXNMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 290, 35));

        lbThongBao.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lbThongBao.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lbThongBao, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 290, 30));

        jXDatePicker2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jXDatePicker2.setDoubleBuffered(true);
        jXDatePicker2.setMaximumSize(new java.awt.Dimension(145, 35));
        jXDatePicker2.setMinimumSize(new java.awt.Dimension(145, 35));
        jXDatePicker2.setPreferredSize(new java.awt.Dimension(145, 35));
        jXDatePicker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker2ActionPerformed(evt);
            }
        });
        getContentPane().add(jXDatePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 187, 190, 35));

        lbBackground.setBackground(new java.awt.Color(255, 255, 255));
        lbBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageGiaoDien/2608782.jpg"))); // NOI18N
        lbBackground.setNextFocusableComponent(this);
        getContentPane().add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //sự kiện click vào thì thoát chương trình
    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
        this.disable();
    }//GEN-LAST:event_btnCloseMouseClicked

    //sự kiện click vào thì màn hình đăng nhập minimize
    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    //sự kiện đưa chuột vào btnClose
    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        // TODO add your handling code here:
        btnClose.setOpaque(true);
        btnClose.setBackground(new Color(213, 208, 208));

    }//GEN-LAST:event_btnCloseMouseEntered

    //sự kiện đưa chuột ra khỏi btnClose
    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        // TODO add your handling code here:
        btnClose.setOpaque(false);
        btnClose.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnCloseMouseExited

    //sự kiện đưa chuột vào btnMinimize
    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        // TODO add your handling code here:
        btnMinimize.setOpaque(true);
        btnMinimize.setBackground(new Color(213, 208, 208));
    }//GEN-LAST:event_btnMinimizeMouseEntered
    //sự kiện đưa chuột vào btnMinimize
    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        // TODO add your handling code here:
        btnMinimize.setOpaque(false);
        btnMinimize.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnMinimizeMouseExited

   //sự kiện đưa chuột vào btn đăng nhập
    private void btnDangNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseEntered
        // TODO add your handling code here:
        lbDangNhap.setForeground(new Color(102, 102, 102));
        btnDangNhap.setkEndColor(new Color(102, 102, 102));
        btnDangNhap.setkStartColor(new Color(255, 255, 255));
        btnDangNhap.setkFillBackground(true);

    }//GEN-LAST:event_btnDangNhapMouseEntered
    //sự kiện đưa chuột ra khỏi btn đăng nhập
    private void btnDangNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseExited
        // TODO add your handling code here:
        lbDangNhap.setForeground(new Color(51, 51, 51));
        btnDangNhap.setkEndColor(new Color(255, 255, 255));
        btnDangNhap.setkStartColor(new Color(102, 102, 102));
        btnDangNhap.setkFillBackground(false);

    }//GEN-LAST:event_btnDangNhapMouseExited
    //sự kiện khi click chuột đăng nhập
    private void lbDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangNhapMouseClicked
        // TODO add your handling code here:
//        final String taiKhoan = tfTaiKhoan.getText();
//        final String matKhau = tfMatKhau.getText();
//        if (taiKhoan.equals("") || matKhau.equals("")) {
//            lbThongBaoDangNhap.setText("Tài khoản hoặc mật khẩu không được để trống");
//            this.validate();
//        } else {
//            final Client client = new Client();
//            this.setCursor(Cursor.WAIT_CURSOR);
//            String id = null;
//            if (!(id = client.dangNhap(taiKhoan, matKhau)).equals("null")) {
//                this.setCursor(Cursor.DEFAULT_CURSOR);
//                lbThongBaoDangNhap.setText("");
//                final String idTaiKhoan = id;
//                java.awt.EventQueue.invokeLater(new Runnable() {
//                    @Override
//                    public void run() {
//                        MainControl main = new MainControl(client, taiKhoan, idTaiKhoan);
//                        main.enable(true);
//                        main.setVisible(true);
//                    }
//                });
//
//                this.dispose();
//                this.setVisible(false);
//            } else {
//                this.setCursor(Cursor.DEFAULT_CURSOR);
//                tfMatKhau.setText("");
//                lbThongBaoDangNhap.setText("Tài khoản hoặc mật khẩu không chính xác");
//                this.validate();
//            }
//        }
    }//GEN-LAST:event_lbDangNhapMouseClicked

    private void lbDangNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangNhapMouseEntered
        // TODO add your handling code here:
        lbDangNhap.setForeground(new Color(102, 102, 102));
        btnDangNhap.setkEndColor(new Color(255, 255, 255));
        btnDangNhap.setkStartColor(new Color(102, 102, 102));
        btnDangNhap.setkFillBackground(true);
    }//GEN-LAST:event_lbDangNhapMouseEntered

    private void lbDangNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangNhapMouseExited
        // TODO add your handling code here:
        lbDangNhap.setForeground(new Color(51, 51, 51));
        btnDangNhap.setkEndColor(new Color(255, 255, 255));
        btnDangNhap.setkStartColor(new Color(102, 102, 102));
        btnDangNhap.setkFillBackground(false);
    }//GEN-LAST:event_lbDangNhapMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void tfMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMatKhauActionPerformed

    private void jXDatePicker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXDatePicker2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private keeptoo.KGradientPanel btnDangNhap;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbDangNhap;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbMatKhau;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbTaiKhoan;
    private javax.swing.JLabel lbTenNguoiDung;
    private javax.swing.JLabel lbThongBao;
    private javax.swing.JLabel lbXacNhanMatKhau;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JPasswordField tfMatKhau;
    private javax.swing.JTextField tfTaiKhoan;
    private javax.swing.JTextField tfTenNguoiDung;
    private javax.swing.JPasswordField tfXNMatKhau;
    // End of variables declaration//GEN-END:variables
}
