/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import BackEndClass.TaiKhoan;
import BackEndClass.ThongTin;
import Client.Client;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
//import java.util.Arrays;
//import java.util.Date;
//import javax.swing.ImageIcon;
//import java.awt.Cursor;

/**
 *
 * @author HiHi
 */
public class DangKyForm extends javax.swing.JFrame {

    /**
     * Creates new form DangNhapForm
     */
    public DangKyForm() {
        this.setUndecorated(true);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        initComponents();
        this.setSize(850, 540);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setBackground(new Color(0, 0, 0, 0));
        tfNgaySinh.setFormats("yyyy-MM-dd");
        tfNgaySinh.getEditor().setBorder(BorderFactory.createEmptyBorder(0, 1, 0, 1));
        tfNgaySinh.getEditor().setOpaque(false);
        JButton btn_pick = (JButton) tfNgaySinh.getComponent(1);
        btn_pick.setOpaque(false);
        btn_pick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageGiaoDien/minus_math_30px.png")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        btnDangNhap = new keeptoo.KGradientPanel();
        lbDangNhap = new javax.swing.JLabel();
        lbTenNguoiDung = new javax.swing.JLabel();
        tfTenNguoiDung = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        lbNgaySinh = new javax.swing.JLabel();
        tfNgaySinh = new org.jdesktop.swingx.JXDatePicker();
        tfTaiKhoan = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        lbTaiKhoan = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        lbMatKhau = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        lbXacNhanMatKhau = new javax.swing.JLabel();
        lbThongBao = new javax.swing.JLabel();
        tfMatKhau = new javax.swing.JPasswordField();
        tfXNMatKhau = new javax.swing.JPasswordField();
        lbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageGiaoDien/icons8_arrow_pointing_left_25px_1.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 40, 40));

        btnMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageGiaoDien/minus_math_30px.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        getContentPane().add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, 40));

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageGiaoDien/multiply_30px.png"))); // NOI18N
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 40, 40));

        btnDangNhap.setBackground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setToolTipText("");
        btnDangNhap.setkBorderRadius(50);
        btnDangNhap.setkEndColor(new java.awt.Color(255, 255, 255));
        btnDangNhap.setkFillBackground(false);
        btnDangNhap.setkGradientFocus(300);
        btnDangNhap.setkStartColor(new java.awt.Color(102, 102, 102));
        btnDangNhap.setkTransparentControls(false);
        btnDangNhap.setOpaque(false);
        btnDangNhap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbDangNhap.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbDangNhap.setForeground(new java.awt.Color(51, 51, 51));
        lbDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDangNhap.setText("Đăng Nhập");
        lbDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDangNhapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbDangNhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbDangNhapMouseExited(evt);
            }
        });
        btnDangNhap.add(lbDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 170, 50));

        lbTenNguoiDung.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lbTenNguoiDung.setForeground(new java.awt.Color(51, 51, 51));
        lbTenNguoiDung.setText("Tên Người Dùng");
        lbTenNguoiDung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbTenNguoiDungKeyPressed(evt);
            }
        });
        getContentPane().add(lbTenNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 190, 30));

        tfTenNguoiDung.setBackground(new java.awt.Color(51, 51, 51));
        tfTenNguoiDung.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfTenNguoiDung.setForeground(new java.awt.Color(51, 51, 51));
        tfTenNguoiDung.setBorder(null);
        tfTenNguoiDung.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfTenNguoiDung.setNextFocusableComponent(tfEmail);
        tfTenNguoiDung.setOpaque(false);
        getContentPane().add(tfTenNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 290, 35));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 290, -1));

        lbEmail.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(51, 51, 51));
        lbEmail.setText("Email");
        getContentPane().add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 190, 30));

        tfEmail.setBackground(new java.awt.Color(51, 51, 51));
        tfEmail.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfEmail.setForeground(new java.awt.Color(51, 51, 51));
        tfEmail.setBorder(null);
        tfEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfEmail.setNextFocusableComponent(lbNgaySinh);
        tfEmail.setOpaque(false);
        getContentPane().add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 290, 35));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 290, -1));

        lbNgaySinh.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lbNgaySinh.setForeground(new java.awt.Color(51, 51, 51));
        lbNgaySinh.setText("Ngày Sinh");
        getContentPane().add(lbNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 190, 30));

        tfNgaySinh.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tfNgaySinh.setDoubleBuffered(true);
        tfNgaySinh.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfNgaySinh.setMaximumSize(new java.awt.Dimension(190, 40));
        tfNgaySinh.setMinimumSize(new java.awt.Dimension(190, 40));
        tfNgaySinh.setNextFocusableComponent(tfTaiKhoan);
        tfNgaySinh.setPreferredSize(new java.awt.Dimension(190, 40));
        getContentPane().add(tfNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 190, 40));

        tfTaiKhoan.setBackground(new java.awt.Color(51, 51, 51));
        tfTaiKhoan.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfTaiKhoan.setForeground(new java.awt.Color(51, 51, 51));
        tfTaiKhoan.setBorder(null);
        tfTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfTaiKhoan.setNextFocusableComponent(tfMatKhau);
        tfTaiKhoan.setOpaque(false);
        getContentPane().add(tfTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 290, 35));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 290, -1));

        lbTaiKhoan.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lbTaiKhoan.setForeground(new java.awt.Color(51, 51, 51));
        lbTaiKhoan.setText("Tài Khoản");
        getContentPane().add(lbTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 190, 30));
        getContentPane().add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 290, -1));

        lbMatKhau.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lbMatKhau.setForeground(new java.awt.Color(51, 51, 51));
        lbMatKhau.setText("Mật Khẩu");
        getContentPane().add(lbMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 190, 30));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 290, -1));

        lbXacNhanMatKhau.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lbXacNhanMatKhau.setForeground(new java.awt.Color(51, 51, 51));
        lbXacNhanMatKhau.setText("Xác Nhận Mật Khẩu");
        getContentPane().add(lbXacNhanMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 190, 30));

        lbThongBao.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lbThongBao.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lbThongBao, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 360, 40));

        tfMatKhau.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfMatKhau.setText("password");
        tfMatKhau.setBorder(null);
        tfMatKhau.setNextFocusableComponent(tfXNMatKhau);
        tfMatKhau.setOpaque(false);
        getContentPane().add(tfMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 290, 35));

        tfXNMatKhau.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfXNMatKhau.setText("password");
        tfXNMatKhau.setBorder(null);
        tfXNMatKhau.setNextFocusableComponent(lbXacNhanMatKhau);
        tfXNMatKhau.setOpaque(false);
        getContentPane().add(tfXNMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 290, 35));

        lbBackground.setBackground(new java.awt.Color(255, 255, 255));
        lbBackground.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lbBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageGiaoDien/2608782.jpg"))); // NOI18N
        lbBackground.setNextFocusableComponent(this);
        getContentPane().add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //check rỗng ở các textfield
    public boolean checkRong() {
        if (tfTenNguoiDung.getText().equals("")) {
            lbThongBao.setText("Bạn Cần Nhập Tên Người Dùng");
            return false;
        } else if (tfEmail.getText().equals("")) {
            lbThongBao.setText("Bạn Cần Nhập Email");
            return false;
        } else if (tfNgaySinh.getDate() == null) {
            lbThongBao.setText("Bạn Cần Chọn Ngày Sinh");
            return false;
        } else if (tfTaiKhoan.getText().equals("")) {
            lbThongBao.setText("Bạn Cần Nhập Tài Khoản");
            return false;
        } else if (tfMatKhau.getText().equals("")) {
            lbThongBao.setText("Bạn Cần Nhập Mật Khẩu");
            return false;
        } else if (tfXNMatKhau.getText().equals("")) {
            lbThongBao.setText("Bạn Cần Xác Nhận Lại Mật Khẩu");
            return false;
        } else if (!tfMatKhau.getText().equals(tfXNMatKhau.getText())) {
            lbThongBao.setText("Mật Khẩu Xác Nhận Không Khớp");
            return false;
        }
        return true;
    }

// <editor-fold defaultstate="collapsed" desc="Button Đăng Ký"> 
    //sự kiện khi click chuột đăng nhập
    private void lbDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangNhapMouseClicked
        Client client = new Client();
        if (client.serverAlive) {
            if (checkRong()) {

                TaiKhoan taiKhoan = new TaiKhoan(tfTaiKhoan.getText(), tfMatKhau.getText());
                ThongTin thongTin = new ThongTin(tfTenNguoiDung.getText(), tfEmail.getText(), new java.sql.Date(tfNgaySinh.getDate().getTime()));
                String[] messReponse = client.guiNguoiDungMoi(taiKhoan, thongTin);
                String thongBao = "";
                for (String s : messReponse) {
                    switch (s) {
                        case "trung_taikhoan":
                            thongBao += "Tài Khoản Đã Tồn Tại \n";
                            break;
                        case "trung_email":
                            thongBao += "Email Đã Có Người Sử Dụng \n";
                            break;
                        case "fail":
                            thongBao += "Đăng Ký Không Thành Công Mời Bạn Thử Lại \n";
                            break;
                        default:
                            break;
                        case "success":
                            JOptionPane.showMessageDialog(null, "Đăng Ký Thành Công", "Đăng Ký", JOptionPane.INFORMATION_MESSAGE);
                            java.awt.EventQueue.invokeLater(new Runnable() {
                                public void run() {
                                    new DangNhapForm().setVisible(true);
                                }
                            });
                            this.dispose();
                            this.disable();
                    }
                }
                lbThongBao.setText(thongBao);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Không Thể Kết Nối Đến Máy Chủ", "Lỗi Kết Nối", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lbDangNhapMouseClicked

    private void lbDangNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangNhapMouseEntered
        // TODO add your handling code here:
        lbDangNhap.setForeground(new Color(102, 102, 102));
        btnDangNhap.setkEndColor(new Color(255, 255, 255));
        btnDangNhap.setkStartColor(new Color(102, 102, 102));
        btnDangNhap.setkFillBackground(true);
    }//GEN-LAST:event_lbDangNhapMouseEntered

    private void lbDangNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangNhapMouseExited
        // TODO add your handling code here:
        lbDangNhap.setForeground(new Color(51, 51, 51));
        btnDangNhap.setkEndColor(new Color(255, 255, 255));
        btnDangNhap.setkStartColor(new Color(102, 102, 102));
        btnDangNhap.setkFillBackground(false);
    }//GEN-LAST:event_lbDangNhapMouseExited
    // </editor-fold> //done
// <editor-fold defaultstate="collapsed" desc="Button Thu nhỏ cửa sổ"> 
    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        // TODO add your handling code here:
        btnMinimize.setOpaque(true);
        btnMinimize.setBackground(new Color(213, 208, 208));
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        // TODO add your handling code here:
        btnMinimize.setOpaque(false);
        btnMinimize.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnMinimizeMouseExited
// </editor-fold> //done
// <editor-fold defaultstate="collapsed" desc="Button Tắt Cửa Sổ"> 
    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
        this.disable();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        // TODO add your handling code here:
        btnClose.setOpaque(true);
        btnClose.setBackground(new Color(213, 208, 208));
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        // TODO add your handling code here:
        btnClose.setOpaque(false);
        btnClose.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnCloseMouseExited
    // </editor-fold> //done
// <editor-fold defaultstate="collapsed" desc="Button Quay lại Đăng Nhập">    
    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapForm().setVisible(true);
            }
        });
        this.dispose();
        this.disable();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        btnBack.setOpaque(true);
        btnBack.setBackground(new Color(213, 208, 208));
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        btnBack.setOpaque(false);
        btnBack.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnBackMouseExited
// </editor-fold> //done
    private void lbTenNguoiDungKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbTenNguoiDungKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTenNguoiDungKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnClose;
    private keeptoo.KGradientPanel btnDangNhap;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbDangNhap;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbMatKhau;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbTaiKhoan;
    private javax.swing.JLabel lbTenNguoiDung;
    private javax.swing.JLabel lbThongBao;
    private javax.swing.JLabel lbXacNhanMatKhau;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JPasswordField tfMatKhau;
    private org.jdesktop.swingx.JXDatePicker tfNgaySinh;
    private javax.swing.JTextField tfTaiKhoan;
    private javax.swing.JTextField tfTenNguoiDung;
    private javax.swing.JPasswordField tfXNMatKhau;
    // End of variables declaration//GEN-END:variables
}
