/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author HiHi
 */
public class MainControl extends javax.swing.JFrame {

    /**
     * Creates new form MainControl
     */
    public MainControl() {
        this.setUndecorated(true);
        initComponents();
        
        JPanel panel1  = new JPanel();
        panel1.setSize(273, 245 );
        panel1.setBackground(Color.red);
        
                JPanel panel2  = new JPanel();
        panel2.setSize(273, 245  );
        panel2.setBackground(Color.yellow);
        panelHinhAnh.add(panel2);
        
                JPanel panel3  = new JPanel();
        panel3.setSize(273, 245  );
        panel3.setBackground(Color.orange);
        panelHinhAnh.add(panel3);
        
                JPanel panel4  = new JPanel();
        panel4.setSize(273, 245 );
        panel4.setBackground(Color.green);
        panelHinhAnh.add(panel4);
        
                JPanel panel5  = new JPanel();
        panel5.setSize(273, 245  );
        panel5.setBackground(Color.gray);
        panelHinhAnh.add(panel5);
        
                JPanel panel6  = new JPanel();
        panel6.setSize(273, 245  );
        panel6.setBackground(Color.black);
        panelHinhAnh.add(panel6);
        
                JPanel panel7  = new JPanel();
        panel7.setSize(273, 245  );
        panel7.setBackground(Color.pink);
        panelHinhAnh.add(panel7);
        
                JPanel panel8  = new JPanel();
        panel8.setSize(273, 245  );
        panel8.setBackground(Color.blue);
        panelHinhAnh.add(panel8);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHead = new javax.swing.JPanel();
        panelNextPage = new javax.swing.JPanel();
        panelFunction = new javax.swing.JPanel();
        panelAnh = new javax.swing.JPanel();
        panelHinhAnh = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1315, 760));
        setMinimumSize(new java.awt.Dimension(1315, 760));
        setPreferredSize(new java.awt.Dimension(1315, 760));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHead.setMaximumSize(new java.awt.Dimension(1314, 135));
        panelHead.setMinimumSize(new java.awt.Dimension(1314, 135));

        javax.swing.GroupLayout panelHeadLayout = new javax.swing.GroupLayout(panelHead);
        panelHead.setLayout(panelHeadLayout);
        panelHeadLayout.setHorizontalGroup(
            panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1315, Short.MAX_VALUE)
        );
        panelHeadLayout.setVerticalGroup(
            panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );

        getContentPane().add(panelHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelNextPage.setBackground(new java.awt.Color(26, 101, 142));

        javax.swing.GroupLayout panelNextPageLayout = new javax.swing.GroupLayout(panelNextPage);
        panelNextPage.setLayout(panelNextPageLayout);
        panelNextPageLayout.setHorizontalGroup(
            panelNextPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1315, Short.MAX_VALUE)
        );
        panelNextPageLayout.setVerticalGroup(
            panelNextPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        getContentPane().add(panelNextPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 707, -1, -1));

        panelFunction.setBackground(new java.awt.Color(26, 101, 142));

        javax.swing.GroupLayout panelFunctionLayout = new javax.swing.GroupLayout(panelFunction);
        panelFunction.setLayout(panelFunctionLayout);
        panelFunctionLayout.setHorizontalGroup(
            panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1315, Short.MAX_VALUE)
        );
        panelFunctionLayout.setVerticalGroup(
            panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        getContentPane().add(panelFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, -1, -1));

        panelAnh.setBackground(new java.awt.Color(0, 0, 153));
        panelAnh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHinhAnh.setMaximumSize(new java.awt.Dimension(1225, 527));
        panelHinhAnh.setMinimumSize(new java.awt.Dimension(1225, 527));
        panelHinhAnh.setName(""); // NOI18N
        panelHinhAnh.setOpaque(false);
        panelHinhAnh.setPreferredSize(new java.awt.Dimension(1225, 527));
        panelHinhAnh.setLayout(new java.awt.GridLayout(2, 4, 45, 45));
        panelAnh.add(panelHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 1230, 527));

        getContentPane().add(panelAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1320, 527));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelAnh;
    private javax.swing.JPanel panelFunction;
    private javax.swing.JPanel panelHead;
    private javax.swing.JPanel panelHinhAnh;
    private javax.swing.JPanel panelNextPage;
    // End of variables declaration//GEN-END:variables
}
