/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Rectangle;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import keeptoo.KTextField;
import BackEndClass.HinhAnh;
import java.util.ArrayList;

/**
 *
 * @author HiHi
 */
public class MainControl extends javax.swing.JFrame {

    /**
     * Creates new form MainControl
     */
    public Client client;
    private ArrayList<HinhAnh> danhSachAnh;

    public MainControl(Client client, String taiKhoan, String id) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        this.setUndecorated(true);
        this.setSize(1315, 760);
        this.initComponents();
        danhSachAnh = client.getDanhSachAnh(id);
        for (HinhAnh ha : danhSachAnh) {
            System.out.println(ha.toString());
        }
//////////////////////////////////////////////////////////////////////////////
        HinhAnhPanel ava = new HinhAnhPanel("3", "3", "4", "5");
//        ava.setImageDisplay(new ImageIcon("imageDemo/55992c240315323aef3cfc264274970d.jpg"));
        panelHinhAnh.add(ava);
        this.validate();

        JPanel panel2 = new JPanel();
        panel2.setSize(273, 245);
        panel2.setBackground(Color.yellow);
        panelHinhAnh.add(panel2);

        JPanel panel3 = new JPanel();
        panel3.setSize(273, 245);
        panel3.setBackground(Color.orange);
        panelHinhAnh.add(panel3);

        JPanel panel4 = new JPanel();
        panel4.setSize(273, 245);
        panel4.setBackground(Color.green);
        panelHinhAnh.add(panel4);

        JPanel panel5 = new JPanel();
        panel5.setSize(273, 245);
        panel5.setBackground(Color.gray);
        panelHinhAnh.add(panel5);

        JPanel panel6 = new JPanel();
        panel6.setSize(273, 245);
        panel6.setBackground(Color.black);
        panelHinhAnh.add(panel6);

        JPanel panel7 = new JPanel();
        panel7.setSize(273, 245);
        panel7.setBackground(Color.pink);
        panelHinhAnh.add(panel7);

        JPanel panel8 = new JPanel();
        panel8.setSize(273, 245);
        panel8.setBackground(Color.blue);
        panelHinhAnh.add(panel8);
//        ImageIcon img = new ImageIcon(getClass().getResource("/image/2608782.jpg"));
//        ava.setImageDisplay(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHead = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        lbTenTaiKhoan = new javax.swing.JLabel();
        lbDungLuong = new javax.swing.JLabel();
        btnChinhSua = new javax.swing.JLabel();
        lbBackground = new javax.swing.JLabel();
        panelNextPage = new javax.swing.JPanel();
        panelFunction = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        panelHinhAnh = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1315, 760));
        setMinimumSize(new java.awt.Dimension(1315, 760));
        setPreferredSize(new java.awt.Dimension(1315, 760));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHead.setMaximumSize(new java.awt.Dimension(1314, 135));
        panelHead.setMinimumSize(new java.awt.Dimension(1314, 135));
        panelHead.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(125);
        kGradientPanel1.setOpaque(false);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        panelHead.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 5, 120, 120));

        lbTenTaiKhoan.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        lbTenTaiKhoan.setForeground(new java.awt.Color(204, 204, 204));
        lbTenTaiKhoan.setText("Hoangbeo69");
        panelHead.add(lbTenTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 200, 50));

        lbDungLuong.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbDungLuong.setText("Dung lượng còn trống 15%");
        panelHead.add(lbDungLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 280, 30));
        panelHead.add(btnChinhSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 30, 30));

        lbBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CoverPage.png"))); // NOI18N
        panelHead.add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1315, 135));

        getContentPane().add(panelHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1315, 135));

        panelNextPage.setBackground(new java.awt.Color(6, 49, 119));
        panelNextPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelNextPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 707, 1320, 60));

        panelFunction.setBackground(new java.awt.Color(6, 18, 52));
        panelFunction.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout panelFunctionLayout = new javax.swing.GroupLayout(panelFunction);
        panelFunction.setLayout(panelFunctionLayout);
        panelFunctionLayout.setHorizontalGroup(
            panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1315, Short.MAX_VALUE)
        );
        panelFunctionLayout.setVerticalGroup(
            panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(panelFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, -1, 50));

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(25, 30, 49));
        kGradientPanel2.setkGradientFocus(0);
        kGradientPanel2.setkStartColor(new java.awt.Color(9, 20, 51));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHinhAnh.setMaximumSize(new java.awt.Dimension(1225, 527));
        panelHinhAnh.setMinimumSize(new java.awt.Dimension(1225, 527));
        panelHinhAnh.setName(""); // NOI18N
        panelHinhAnh.setOpaque(false);
        panelHinhAnh.setPreferredSize(new java.awt.Dimension(1225, 527));
        panelHinhAnh.setLayout(new java.awt.GridLayout(2, 4, 45, 45));
        kGradientPanel2.add(panelHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 7, 1230, 520));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1320, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                MainControl main = new MainControl().setVisible(true);
//            }
//        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnChinhSua;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbDungLuong;
    private javax.swing.JLabel lbTenTaiKhoan;
    private javax.swing.JPanel panelFunction;
    private javax.swing.JPanel panelHead;
    private javax.swing.JPanel panelHinhAnh;
    private javax.swing.JPanel panelNextPage;
    // End of variables declaration//GEN-END:variables

}
